#!/usr/bin/env python3
"""Transform the workflow result into: sections.json (for the PDF builder),
VIDEO_PROMPT.md, and HACKATHON_FIT_AND_REVIEW.md."""
import json
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = r"C:\Users\ELANGO~1\AppData\Local\Temp\claude\C--Users-Elangovan\519a22a6-8a15-4bd2-aa84-da580b035292\tasks\wr72l1g4o.output"

data = json.load(open(SRC, "r", encoding="utf-8"))
res = data["result"]
sections = sorted(res["sections"], key=lambda s: s["order"])


def clean_heading(h):
    return re.sub(r"^\s*\d+[.)]\s*", "", h).strip()


# ── 1. sections.json for the PDF builder ────────────────────────────────────
meta = {
    "eyebrow": "PRODUCT PROPOSAL  ·  FOR NOTEBOOKLM",
    "title": "Receipts",
    "tagline": "No source, no claim.",
    "subtitle": "Competitive teardowns that show their sources.\n"
                "A complete product proposal — prepared for NotebookLM ingestion.",
    "meta_lines": [
        "WORLD PRODUCT DAY 2026  ·  “EVERYONE SHIPS NOW”",
        "MIND THE PRODUCT  ×  PENDO",
        "github.com/elangovanvp/Receipts",
        "Document version 1.0  ·  June 2026",
    ],
}

out_sections = []
for s in sections:
    out_sections.append({
        "heading": clean_heading(s["heading"]),
        "subtitle": s.get("subtitle", ""),
        "body_markdown": s["body_markdown"],
    })

json.dump({"meta": meta, "sections": out_sections},
          open(os.path.join(HERE, "sections.json"), "w", encoding="utf-8"),
          ensure_ascii=False, indent=2)
print("sections.json:", len(out_sections), "sections")

# ── 2. VIDEO_PROMPT.md ──────────────────────────────────────────────────────
vp = res["videoPrompt"]
# Strip any leaked conversational preamble before the first Markdown heading.
m = re.search(r"(?m)^#\s", vp)
if m:
    vp = vp[m.start():]
note = (
    "> _For the World Product Day 2026 hackathon (sub-3-minute demo video "
    "requirement). Contains an AI text-to-video master prompt, per-shot image "
    "prompts, a voiceover script, and a screen-recording fallback._\n\n"
)
# Insert the note right after the document's own H1 title line.
lines = vp.split("\n")
vp_out = lines[0] + "\n\n" + note + "\n".join(lines[1:]).lstrip("\n")
open(os.path.join(HERE, "VIDEO_PROMPT.md"), "w", encoding="utf-8").write(vp_out)
print("VIDEO_PROMPT.md:", len(vp_out), "chars")

# ── 3. HACKATHON_FIT_AND_REVIEW.md ──────────────────────────────────────────
pf = res["psFit"]
cr = res["codeReview"]
L = []
L.append("# Receipts — Problem-Statement Fit & Pre-Submission Review\n")
L.append("_An honest, judge's-eye assessment of how Receipts maps to the World "
         "Product Day 2026 rubric, plus a pre-deploy code review. Generated by a "
         "multi-agent analysis of the live repo._\n")
L.append("\n## Overall verdict\n")
L.append("**Alignment score: %s / 100**\n" % pf["alignment_score_0_100"])
L.append("\n%s\n" % pf["overall_verdict"])

L.append("\n## Judging rubric — axis by axis (each 25%)\n")
for c in pf["criteria"]:
    L.append("\n### %s  —  self-score %s / 25\n" %
             (c["name"], c.get("self_score_0_25", "?")))
    L.append("**How Receipts meets it:** %s\n" % c["how_receipts_meets_it"])
    if c.get("gaps_or_risks"):
        L.append("\n**Gaps / risks a skeptical judge will probe:** %s\n" % c["gaps_or_risks"])

if pf.get("judge_fit"):
    L.append("\n## Fit to each named judge\n")
    for j in pf["judge_fit"]:
        L.append("- **%s** — %s" % (j["judge"], j["why_it_lands"]))
    L.append("")

L.append("\n## Mandatory submission requirements — status\n")
L.append("| Requirement | Status | Action needed |")
L.append("|---|---|---|")
for m in pf["mandatory_requirements"]:
    act = m.get("action_needed", "").replace("\n", " ")
    L.append("| %s | %s | %s |" % (m["requirement"], m["status"].split(".")[0], act[:200]))
L.append("")

if pf.get("mismatches_or_red_flags"):
    L.append("\n## Red flags to manage\n")
    for r in pf["mismatches_or_red_flags"]:
        L.append("- %s" % r)
    L.append("")

L.append("\n## Top recommendations (in priority order)\n")
for i, r in enumerate(pf["top_recommendations"], 1):
    L.append("%d. %s" % (i, r))
L.append("")

L.append("\n---\n\n## Pre-deploy code review\n")
L.append("**Deploy readiness:** %s  \n" % cr["deploy_readiness"])
L.append("**Build status:** %s\n" % cr["build_status"])
L.append("\n### Findings\n")
if cr["issues"]:
    L.append("| Severity | Area | Finding | Recommended fix |")
    L.append("|---|---|---|---|")
    for it in cr["issues"]:
        L.append("| %s | %s | %s | %s |" %
                 (it["severity"].upper(), it["area"],
                  it["finding"].replace("\n", " "), it["fix"].replace("\n", " ")))
else:
    L.append("_No issues found._")
L.append("")
if cr.get("things_that_are_correct"):
    L.append("\n### Verified correct\n")
    for t in cr["things_that_are_correct"]:
        L.append("- %s" % t)
    L.append("")

open(os.path.join(HERE, "HACKATHON_FIT_AND_REVIEW.md"), "w", encoding="utf-8").write("\n".join(L))
print("HACKATHON_FIT_AND_REVIEW.md written")
print("DONE")
